service: serverless-flask

plugins:
  - serverless-python-requirements
  - serverless-wsgi
package:
  exclude:
    - 'venv/**'
custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
    slim: true

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1

functions:
  python3:
    handler: wsgi_handler.handler
    events:
      - http:
          method: post
          path: /python3
          cors: false