service: api 

provider:
  name: aws
  stage: dev
  region: us-east-1

resources:
  Resources:
    LanguagesApiGw:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: LanguagesApiGw

  Outputs:
    apiGatewayRestApiId:
      Value:
        Ref: LanguagesApiGw
      Export:
        Name: LanguagesApiGw-restApiId

    apiGatewayRestApiRootResourceId:
      Value:
        Fn::GetAtt:
          - LanguagesApiGw
          - RootResourceId
      Export:
        Name: LanguagesApiGw-rootResourceId
