service: api 

custom:
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  stage: dev
  region: us-east-1

resources:
  Resources:
    LanguagesApiGw:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: LanguagesApiGw-${self:custom.stage}

  Outputs:
    apiGatewayRestApiId:
      Value:
        Ref: LanguagesApiGw
      Export:
        Name: LanguagesApiGw-restApiId-${self:custom.stage}

    apiGatewayRestApiRootResourceId:
      Value:
        Fn::GetAtt:
          - LanguagesApiGw
          - RootResourceId
      Export:
        Name: LanguagesApiGw-rootResourceId-${self:custom.stage}
