name: Deploy

on:
  push:
    branches:
      - master
      - cf-vierfy
jobs:
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
      general: ${{ steps.filter.outputs.general }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2.2.1
        id: filter
        with:
          filters: |
            general: 
              - '.github/**/*'
            backend:
              - 'serverless.yml'
              - 'test_jsons/**/*'
              - 'python/**/*'
            frontend:
              - 'frontend/**/*'
  gh-pages:
    name: Deploying to Github Pages
    needs: [changes]
    if: ${{ needs.changes.outputs.frontend == 'true' || needs.changes.outputs.general == 'true' }}
    defaults:
      run:
        working-directory: frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run deploy script
        run: |
          .github/deploy.sh
