name: Generate static json results
on:
  push:
    branches:
      - master
    paths-ignore:
      - frontend/**
jobs:
  python3_benchmark:
    name: Run python benchmark
    runs-on: ubuntu-latest
    strategy:
      matrix:
#        python-version: [ '2', '3', 'pypy2', 'pypy3' ]
        python-version: [ '2', '3' ]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python-version }}.x"

      - name: Install requirements
        run: pip install -r requirements_py${{ matrix.python-version }}.txt

      - name: Run benchmark
        run: |
          python main.py
          mv results.json frontend/src/generated_results/python${{ matrix.python-version }}.json

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "[auto] Update Results"
          title: "[auto] Updated Results for Python ${{ matrix.python-version }}"
          assignees: ronlut
          branch: auto-results/python${{ matrix.python-version }}
