name: Generate static json results
on:
  push:
    branches:
      - master
      - refactor_ci
    paths-ignore:
      - frontend/**
jobs:
  python-benchmark:
    name: Run python benchmarks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python
    strategy:
      matrix:
        version: [2, 3]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.version }}.x"

      - name: Install requirements
        run: pip install -r requirements_py${{ matrix.version }}.txt

      - name: Run benchmark
        run: |
          python main.py
          mv results.json python${{ matrix.version }}.json

      - uses: actions/upload-artifact@v2
        with:
          path: ./python/python${{ matrix.version }}.json

  create-pull-request:
    needs: ['python-benchmark']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        id: download
        with:
          name: artifact
          path: ./frontend/src/generated_results  

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "[auto] Update Results"
          title: "[auto] Updated Results"
          assignees: ronlut
          branch: update-results
