name: Generate static json results
on:
  push:
    branches:
      - master
    paths-ignore:
      - frontend/**
jobs:
  python-benchmark:
    name: Run python benchmarks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python
    strategy:
      matrix:
        version: [2, 3]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.version }}.x"

      - name: Install requirements
        run: pip install -r requirements_py${{ matrix.version }}.txt

      - name: Run benchmark
        run: |
          python main.py
          mv results.json python${{ matrix.version }}.json

      - uses: actions/upload-artifact@v2
        with:
          path: ./python/python${{ matrix.version }}.json
  java-benchmark:
    name: Run java benchmarks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: java
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run benchmark
        run: |
          java -cp target/java-dev.jar com.jsonperf.jobs.GenerateResults
          mv results.json java.json

      - uses: actions/upload-artifact@v2
          with:
            path: ./java/java.json

  create-pull-request:
    needs: ['python-benchmark', 'java-benchmark']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        id: download
        with:
          name: artifact
          path: ./frontend/src/generated_results

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "[auto] Update Results"
          title: "[auto] Updated Results"
          assignees: ronlut
          branch: update-results
