name: Deploy to github pages
defaults:
  run:
    working-directory: frontend
on:
  push:
    branches:
      - master
    paths:
      - frontend/**
jobs:
  pre-ci:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: 'Block Concurrent Executions'
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  gh-pages-deploy:
    name: Deploying to gh-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run deploy script
        run: |
          .github/deploy.sh
