name: Generate static json results test
on:
  push:
    branches:
      - test_cpr
jobs:
  python-benchmark:
    name: Run python benchmarks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python
    strategy:
      matrix:
        version: [2, 3]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.version }}"

      - name: Install requirements
        run: pip install -r requirements_py${{ matrix.version }}.txt

      - name: Run benchmark
        run: |
          python main.py
      - run: ls -R

      - uses: actions/upload-artifact@v2
        with:
          name: python${{ matrix.version }}.json
          path: ./python/results.json
  create-pull-request:
    needs: ['python-benchmark']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # This will download all artifacts created during the workflow to the root of the repository
      - uses: actions/download-artifact@v2
        with:
          path: ./artifacts
      
      - name: Display structure of downloaded files
        run: ls -R ./artifacts

      - name: 'Echo download path'
        run: echo ${{steps.download.outputs.download-path}}   

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "[auto] Update Results"
          title: "[auto] Updated Results"
          assignees: ronlut
          branch: auto-results/test_cpr
